# Generated by Django 4.1.6 on 2023-02-09 11:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('start_time_booking', models.DateTimeField()),
                ('finish_time_booking', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Товар')),
                ('count', models.IntegerField(verbose_name='Объем/количество')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название группы')),
                ('count_guests', models.IntegerField(default=1, verbose_name='Количество гостей')),
                ('tag', models.CharField(max_length=25, verbose_name='Тmiег группы')),
                ('group_organizer', models.CharField(max_length=256, verbose_name='Имя инструктора')),
                ('date_checkin', models.DateField(verbose_name='Дата заселения')),
                ('date_checkout', models.DateField(verbose_name='Дата выселения')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя отеля')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('goods_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.goods')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
            bases=('crm.goods',),
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('goods_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.goods')),
            ],
            options={
                'verbose_name': 'Хозтовар',
                'verbose_name_plural': 'Хозтовары',
            },
            bases=('crm.goods',),
        ),
        migrations.CreateModel(
            name='Sauna',
            fields=[
                ('bookingservices_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.bookingservices')),
            ],
            options={
                'verbose_name': 'Сауна',
                'verbose_name_plural': 'Сауны',
            },
            bases=('crm.bookingservices',),
        ),
        migrations.CreateModel(
            name='YogaHall',
            fields=[
                ('bookingservices_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.bookingservices')),
            ],
            options={
                'verbose_name': 'Йога хол',
                'verbose_name_plural': 'Йога холы',
            },
            bases=('crm.bookingservices',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=100, verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Название номера')),
                ('capacity', models.IntegerField(default=2, verbose_name='Количество мест')),
                ('over_booking', models.IntegerField(default=1, verbose_name='Дополнительные места в номер')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.hotel')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('surname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('telephone', models.CharField(max_length=256, verbose_name='Телефон')),
                ('date_checkin', models.DateField(blank=True, verbose_name='Дата заселения')),
                ('date_checkout', models.DateField(blank=True, verbose_name='Дата выселения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.group')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('surname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.position')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomes', models.IntegerField(verbose_name='Входящие средства')),
                ('outcomes', models.IntegerField(verbose_name='Расходы')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата и время операции')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.employee')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.group')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.guest')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.service')),
            ],
            options={
                'verbose_name': 'Касса',
            },
        ),
        migrations.AddField(
            model_name='bookingservices',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.group'),
        ),
        migrations.AddField(
            model_name='bookingservices',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.guest'),
        ),
    ]
