# Generated by Django 4.1.6 on 2023-02-13 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_group_hotel_alter_group_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('Предварительная регистрация', 'предварительная регистрация'), ('Регистрация', 'регистрация'), ('В отеле', 'в отеле'), ('Завершен', 'завершен')], default='Предварительная регистрация', max_length=30, verbose_name='Статус группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.hotel', verbose_name='Отель'),
        ),
    ]
