# Generated by Django 4.1.6 on 2023-02-14 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_employee_name_remove_employee_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='fullness',
            field=models.CharField(choices=[('полный', 'полный'), ('частично', 'частично'), ('пустой', 'пустой')], default='пустой', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.position'),
        ),
    ]
