# Generated by Django 4.1.6 on 2023-02-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_room_fullness_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number_guests',
            field=models.IntegerField(default=0, verbose_name='Количество гостей'),
        ),
        migrations.AlterField(
            model_name='room',
            name='fullness',
            field=models.CharField(choices=[('full', 'Полный'), ('partially', 'Частично'), ('empty', 'Пустой'), ('over', 'Переполненный')], default='Пустой', max_length=30, verbose_name='Статус'),
        ),
    ]
