# Generated by Django 4.1.6 on 2023-02-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_goods_unit_alter_group_status_alter_room_fullness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='count',
            field=models.FloatField(verbose_name='Объем/количество'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
    ]
