# Generated by Django 4.1.6 on 2023-02-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_goods_count_alter_goods_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='how_many_unit',
            field=models.IntegerField(default=1, verbose_name='Количество единиц'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(verbose_name='Стоимость за единицу'),
        ),
    ]
