# Generated by Django 4.1.6 on 2023-02-21 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_goods_count_alter_goods_how_many_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.hotel'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='count',
            field=models.FloatField(default=0, verbose_name='Объем/количество в единице'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.group'),
        ),
    ]
