# Generated by Django 4.1.6 on 2023-02-21 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_employee_hotel_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hotel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.hotel'),
        ),
    ]
