# Generated by Django 4.1.6 on 2023-02-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_employee_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
