# Generated by Django 4.1.6 on 2023-02-22 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_goods_date_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='date_update',
        ),
        migrations.CreateModel(
            name='InventoryControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.employee')),
            ],
        ),
    ]
