# Generated by Django 4.1.6 on 2023-02-22 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0016_remove_goods_date_update_inventorycontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycontrol',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
