# Generated by Django 4.1.6 on 2023-02-24 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_inventorycontrol_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorycontrol',
            old_name='data_update',
            new_name='date_update',
        ),
    ]
