# Generated by Django 4.1.6 on 2023-03-02 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_rename_data_update_inventorycontrol_date_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorycontrol',
            options={'verbose_name': 'Складской учет'},
        ),
        migrations.RemoveField(
            model_name='guest',
            name='date_checkin',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='date_checkout',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checkin', models.DateField(verbose_name='Дата заселения')),
                ('date_checkout', models.DateField(verbose_name='Дата выселения')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.guest')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.room')),
            ],
        ),
    ]
