# Generated by Django 4.1.6 on 2023-03-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_alter_inventorycontrol_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='guest',
            name='telephone',
            field=models.CharField(max_length=512, verbose_name='Телефон'),
        ),
    ]
