# Generated by Django 4.1.6 on 2023-03-14 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_rename_name_guest_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.room'),
            preserve_default=False,
        ),
    ]
