# Generated by Django 4.1.6 on 2023-04-19 03:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_remove_booking_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashier',
            old_name='datetime',
            new_name='date_create',
        ),
        migrations.AddField(
            model_name='cashier',
            name='cashless',
            field=models.BooleanField(default=False, verbose_name='Безнал'),
        ),
        migrations.AddField(
            model_name='cashier',
            name='date_service',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата услуги'),
        ),
        migrations.AddField(
            model_name='cashier',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.hotel', verbose_name='Объект'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='in_hotel',
            field=models.BooleanField(default=True, verbose_name='В отеле'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.employee'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.guest'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='incomes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Приход(сумма)'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='outcomes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Расходы(сумма)'),
        ),
    ]
