# Generated by Django 4.1.6 on 2023-04-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_rename_datetime_cashier_date_create_cashier_cashless_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.guest', verbose_name='Гость'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.service', verbose_name='Услуга'),
        ),
    ]
