# Generated by Django 4.1.6 on 2023-04-25 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_alter_cashier_employee_alter_cashier_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='guest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.guest', verbose_name='Гость'),
        ),
    ]
