# Generated by Django 4.1.6 on 2023-04-25 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_alter_cashier_employee_alter_cashier_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.service', verbose_name='Услуга'),
        ),
    ]
