# Generated by Django 4.1.6 on 2023-04-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_categoryincome_categoryoutcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='incomes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Приход(сумма)'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='outcomes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Расходы(сумма)'),
        ),
    ]
