# Generated by Django 4.1.6 on 2023-04-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_alter_cashier_comment_alter_cashier_incomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='incomes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Приход(сумма)'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='outcomes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Расходы(сумма)'),
        ),
    ]
